### ISSUE TITLE
Interactive exercises in JS

### ISSUE THREAD

**Issue by Gustrucco** [mumuki/mumuki-javascript-runner#16]

**Comment by flbulgarelli** [comment]
This should require an a `TryHook` that works similar to than on `bash-runner` https://github.com/mumuki/mumuki-bash-runner/blob/master/lib/try_hook.rb

**Comment by afska** [comment]
The only difference with the [current query hook](https://github.com/mumuki/mumuki-javascript-runner/blob/master/lib/query_hook.rb) is that these exercises should have a goal, right?

**Comment by flbulgarelli** [comment]
Right!

**Comment by flbulgarelli** [comment]
It would be nice if you could extract the very similar logic to a single place.
