### ISSUE TITLE
Quotes are added to a record's key when they shouldn't

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mumuki-javascript-runner#17]
![image](https://user-images.githubusercontent.com/11304439/52811452-e3a31980-3073-11e9-9091-d697d68ea1d9.png)

Where it should be like this, without double quotes on the keys:

```javascript
ム var test = { key1: 3, key2: "hi" }
=> undefined
ム test
=> {key1:3,key2:"hi"}
```

**Comment by flbulgarelli** [comment]
@julian-berbel says the only possible solution to this is by removing the quotes with a regexp :man_shrugging:

**Comment by flbulgarelli** [comment]
Or perhaps we could reimplement the toString to not use `JSON.stringify` but a custom method instead
